### ISSUE TITLE
Game yml file structure

### ISSUE THREAD

**Issue by alesrebec** [ChunkDev/pintrix_matrices#1]
There are a couple of improvements I would suggest for the current yml structure.

- Moving the game information from bottom to top
- "Lamp" and "Switch" to lowercase ("lamp" and "switch") because they are the only two keys starting with uppercase letter.
- Renaming "matrixItems" to "matrixElements" to be mathematically correct about matrix terminology. Source: [Matrix wiki](https://en.wikipedia.org/wiki/Matrix_(mathematics))
- Simlification of the element names: columnIdentifier -> column, rowIdentifier -> row, itemName -> name, and moving row under column to be closed together for better DX.

Extra:
- Naming the yml files with "GAME NAME" will eventually clash with a game with the same name. It would be good to thing about having a unique format for game file name. Something like: Game_Name_Year.yml or GameName_Year_Manufacturer.yml.

**Comment by ChunkDev** [comment]
All suggestions added in https://github.com/ChunkDev/pintrix_matrices/commit/e1dd459b9d51f9015cf9bfc52cb260bba7423da4
